{% set name = "affinder" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/affinder-{{ version }}.tar.gz
  sha256: 1f9281e4f4a41340e5e1b479e5e375c8abb984ae2f1e629147352cfec24ca085

build:
  entry_points:
    - affinder=affinder.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - magicgui >=0.3.7
    - napari >=0.4.17
    - npe2 >=0.1.2
    - numpy
    - python >={{ python_min }}
    - scikit-image >=0.19.2
    - toolz

test:
  imports:   # [not linux]
    - affinder  # [not linux]
  commands:
    - pip list
    - pip check
    - export QT_DEBUG_PLUGINS=1  # [not win]
    - affinder --help  # [not linux]
    - "DISPLAY=localhost:1.0 xvfb-run -a affinder --help"  # [linux]
    - "DISPLAY=localhost:1.0 xvfb-run -a python -c 'import affinder'"  # [linux]
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/jni/affinder
  summary: Quickly find the affine matrix mapping one image to another using manual correspondence points annotation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jni
