{% set name = "affinder" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/affinder-{{ version }}.tar.gz
  sha256: 509730f27199c3b18a2699a11b274aee851613eaeb1532b993242c78bf1733bb

build:
  entry_points:
    - affinder=affinder.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - magicgui >=0.3.7
    - napari >=0.4.17
    - npe2 >=0.1.2
    - numpy
    - python >=3.9
    - scikit-image >=0.19.2
    - toolz

test:
  imports:   # [not linux]
    - affinder  # [not linux]
  commands:
    - pip list
    - pip check
    - export QT_DEBUG_PLUGINS=1  # [not win]
    - affinder --help  # [not linux]
    - "DISPLAY=localhost: 1.0 xvfb-run -a affinder --help"  # [linux]
    - "DISPLAY=localhost: 1.0 xvfb-run -a python -c 'import affinder'"  # [linux]
  requires:
    - pip

about:
  home: https://github.com/jni/affinder
  summary: Quickly find the affine matrix mapping one image to another using manual correspondence points annotation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - jni
